shutdown_costmaps: false
footprint_padding: 0.01
controller_frequency: 10.0
controller_patience: 3.0

planner_frequency: 20.0
planner_patience: 5.0

oscillation_timeout: 30.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true
