#settings for the mapserver. Detailed descriptions of these parameters can be found at http://www.ros.org/wiki/map_server
image: ../map/tree.pgm
resolution: 0.010000
origin: [-5.000000, -5.000000, 0.000000]
occupied_thresh: 0.65
free_thresh: 0.196
negate: 0
mode: trinary
