#This file contains common configuration options for the two costmaps used in the navigation stack for more details on the parameters in this file, and a full list of the parameters used by the costmaps, please see http://www.ros.org/wiki/costmap_2d

#For this example we'll configure the costmap in voxel-grid mode
#voxel
map_type: costmap
robot_base_frame: base_link
#Voxel grid specific parameters
origin_z: 0.0
z_resolution: 0.2
z_voxels: 10
unknown_threshold: 9
mark_threshold: 0

#Set the tolerance we're willing to have for tf transforms efk override was .3
transform_tolerance: 0.5

#Obstacle marking parameters efk override was 2.5,2,3.0
obstacle_range: 3.0
max_obstacle_height: 2.55
raytrace_range: 4.0
#.3050 by 3050
#The footprint of the robot and associated padding
footprint: [[-0.2225, -0.1525], [-0.2225, 0.1525], [0.0825, 0.1525], [0.0825, -0.1525]]

footprint_padding: 0.05

#inflation Cost function parameters efk override was .55 and 10
inflation_radius: 0.2 
cost_scaling_factor: 5.0

#The cost at which a cell is considered an obstacle when a map is read from the map_server
lethal_cost_threshold: 100

#from https://github.com/kth-ros-pkg/ridgeback/blob/master/ridgeback_navigation/params/costmap_common_params.yaml
plugins:
- {name: static_map,       type: "costmap_2d::StaticLayer"}
- {name: obstacles_layer, type: "costmap_2d::ObstacleLayer"}
- {name: inflater_layer, type: "costmap_2d::InflationLayer"}

#Configuration for the sensors that the costmap will use to update a map
obstacles_layer:
  observation_sources: scan
  scan: {data_type: LaserScan, expected_update_rate: 0.4,
  observation_persistence: 0.0, marking: true, clearing: true, max_obstacle_height: 0.4, min_obstacle_height: 0.08}
